services:
  web:
    container_name: visahack_web
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    restart: always
    volumes:
      - "./:/var/www/html/"
      - "./container_resource/php/xdebug-local.ini:/usr/local/etc/php/conf.d/xdebug-local.ini"
      # - "./logs/apache2:/var/log/apache2/"
      - "./container_resource/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    ports:
      - "8000:80"
      - "5173:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    container_name: visahack_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: visahack
    ports:
      - "3309:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
